### ISSUE TITLE
Conectar Base de datos en ambientes de despliegue

### ISSUE THREAD

**Issue by neodevelop** [makingdevs/Ienpop-website#17]
Hacer la configuración necesaria para los ambientes de qa, stage y prod, a través del archivo *database.yml*.

Este archivo lo vinculan Capistrano en el despliegue, y sólo es necesario hacer la configuración en la lectura de la base de datos.

**Comment by onahump** [comment]
@neodevelop queda pendiente la externalización de los datos

**Comment by vanemily** [comment]
Para poder leer un archivo yml en sinatra, requerimos de :
```ruby
require "sinatra/config_file"
``` 

Como tenemos una aplicación modular, necesitamos de registrar la configuración 
```ruby
register Sinatra::ConfigFile
config_file 'config/config.yml'
puts settings.db['siyen_db']
```

Refiere al commit:  6546e03
