### ISSUE TITLE
Diseño de los datos de Encargados

### ISSUE THREAD

**Issue by onahump** [makingdevs/Ienpop-website#30]
Se creo un archivo donde están almacenados todos los encargados, la información que se esta guardo es la siguiente: Nombre, área (de jurisdicción) y la dirección de correo electrónico.

Posteriormente se creo un modelo en Ruby con Sinatra de Encargados, con los atributos de  instancia: Nombre, area y correo.

**Comment by vanemily** [comment]
To read a JSON file from uri, we need the following:
 ```ruby
  require 'json'
  require 'net/http'

  uri = URI.parse("http://training.makingdevs.com.s3.amazonaws.com/manager.json")
  content = Net::HTTP.get_response uri
  values = JSON.parse(content.body)

```
