### ISSUE TITLE
Agregar mensaje de correo enviado exitosamente

### ISSUE THREAD

**Issue by onahump** [makingdevs/Ienpop-website#44]
Mostrar en la vista un mensaje de que el correo fue enviado exitosamente o en caso de que no se haya podido realizar el envío del mismo, mostrar un mensaje al usuario que la acción no se pudo realizar.

**Comment by vanemily** [comment]
Para poder enviar el mensaje se utilizo flash, lo cual nos permite guardar información entre requests

Instalamos la gema 

```ruby
sinatra-flash
```

**Comment by vanemily** [comment]
Para poder usarla, en caso de tener una aplicación modular, agregamos lo siguiente:

```ruby
   enable :sessions
   register Sinatra::Flash
``` 

session -> Nos permite guardar información entre un request y otro. 

```ruby
   flash[:message] = "Este es un mensaje informativo."
```

Refiere al commit : dd078f7

**Comment by vanemily** [comment]
Para poder hacer que se muestre en la vista:

```ruby
<%  if flash[:message] %>
```

Refiere al commit 852b73d

**Comment by vanemily** [comment]
Podemos tener varios tipos de flash y dependiendo del valor de estos, que se muestren en la vista.

```ruby
 <%  if flash[:success] %>
     <h1><%= flash[:success] %></h1>
 <% end %>
 <%  if flash[:warning] %>
    <h1><%= flash[:warning] %></h1>
 <% end %>
```

Refiere al commit: de35878
