### ISSUE TITLE
No se puede enviar correo 

### ISSUE THREAD

**Issue by onahump** [makingdevs/Ienpop-website#48]
Al enviar el correo electrónico, ocurrió un error de tipo OpenTimeout.

**Comment by vanemily** [comment]
Se agrego un bloque rescue, en caso de que ocurra un error al enviar el correo electrónico de la sede seleccionada y  la sede principal (CDMX), muestre un mensaje  de que no se pudo realizar la acción. 
Este bloque contiene el método que se encarga de enviar el correo, como se muestra a continuación:
```ruby
begin     
       message = Mail.deliver({:to => "#{sede}",
             :from => ENV["USER_NAME"],
             :cc => "#{central_sede_email}",
             :subject => "#{subject}",
             :body => "#{message} \nMensaje enviado por #{name_contact}, con el siguiente correo de contacto #{email}"
             })
     rescue  
        puts 'Ocurrió un error al enviar el correo.'
     end  
        puts 'Correo enviado exitosamente.'
    end
```
